### ISSUE TITLE
[BUG]TX Profile - TX Bandwidth filter value entry 

### ISSUE THREAD

**Issue by VK1HX** [ramdor/Thetis#301] opened 2023-11-28 06:43 UTC
When creating a TX profile from the setup - Transmit Tab with Thetis v2.10.3.4, and you change the TX bandwidth Filter value of the "High" value the box auto populates numbers which do not correspond with what you enter on the keyboard.

To reproduce the issue:
1. go to the Transmit Tab in Thetis setup.
2. Change the value of Transmit Filter - High, from a default value of 3000 to 2900. 

As you go to enter the first number "2" the box auto populates two zeros after the number 2. If you type 29 is will populate a value outside the allowed maximum value.

This issue appears to be in versions, 2.10.3.4, 2.10.3.3, 2.10.2.2 that I have tested, but is not present in Thetis versions 2.9.x.x.

Cheers
Phil - VK1HX

**Comment by ramdor** [comment] 2023-11-28 17:01
it is caused by the code that is checking for changes in the TX profile. Will be fixed for 2.10.3.5. Thanks for the report Phil. Cheers.

**Closed** 2023-11-28 17:11 UTC
Labels: bug
