### ISSUE TITLE
[BUG] When SWR Protection 'Enable Protection' is checked and 'Ignore when Tune Pwr' is not checked, multiple TUN events will trigger the 'High SWR' red box warning only every other time.

### ISSUE THREAD

**Issue by n1gp** [ramdor/Thetis#538] opened 2024-11-30 10:33 UTC
Check SWR Protection 'Enable Protection', in Ant/Filters Setup page,
leave 'Ignore when Tune Pwr' unchecked,
put rig on a load that will give an SWR mismatch > the SWR Protection setting,
press TUN to trigger the 'High SWR' red box warning,
release and press TUN and note the 'High SWR' red box warning does not happen and 0 watts output occurs.
If triggered again the 'High SWR' red box warning will occur. It happens every other time.

Expected behaviour is that the warning should occur every time.

I had output power set to 20 Watts and into a load that had a 5:1 SWR mismatch.
The 'Enable Protection SWR' was left at the default 2.1:1

I traced this behaviour back to commit e9c9da1, 'general backup commit - amplifier, power limit system, fixes for compressed view'
before that it did not happen.

This was tested on an ANAN-7000DLE with v2.2.2 (or 2.2.5) P2, and also v2.7 (Orion_MkII_v2.7_K5SO_5-4) P1 firmware.

Resetting the DB didn't change the behaviour.

OS: Windows 10

**Comment by ramdor** [comment] 2024-11-30 13:15
now resolved in 2.3.10.7. Caused by the swrprotect value only being used when SetOutputPower was called, and in later versions of thetis this was prevented if the power levels were kept the same between tx's. Also took the opportunity to fix the swr protect thread code that didn't update radio.audiovolume, and there is now an option in alex tab to cause power wind back on high swr.

**Closed by ramdor** 2024-11-30 13:15 UTC
Labels: bug
