### ISSUE TITLE
[FEATURE]tci

### ISSUE THREAD

**Issue by Alan5596** [ramdor/Thetis#198] opened 2023-10-09 19:50 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ramdor** [comment] 2023-10-09 20:55
Alan, It looks like you just posted an empty feature TCI request and didn't make any changes to the example template. Can you update it or I can close it and you can add another? Up to you.

Richie.

**Comment by Alan5596** [comment] 2023-10-09 22:36
Hi Richie,I made a mistake, please just close it.  I’m not too familiar with GitHub.  I was going to ask about TCI and SDC but I see that it the frequency bug may be fixed in the next release, which is great news.  Thanks for all your work and Thetis is the most intuitive software I have used with any SDR.Cheers,Alan.On 9 Oct 2023, at 21:55, Richie ***@***.***> wrote:﻿
Alan, It looks like you just posted an empty feature TCI request and didn't make any changes to the example template. Can you update it or I can close it and you can add another? Up to you.
Richie.

**Comment by ramdor** [comment] 2023-10-10 03:00
yes there was an issue that I found and fixed, hopefully it is related to the issue you are having. You can try the pre-release if you want, but the final 2.10.2 will be out in a few days fingers crossed.

**Comment by ramdor** [comment] 2023-10-18 22:11
cw pitch will be in the IF message when CTUN is off, because the spectral area will be centred at current DDS. The if: will in this case be the required shift to ddds which will be the cw offset. I have double and tripple checked this and it looks ok. I dont have a current version of SDC unfortunately.

I made a video whilst checking it earlier : https://youtu.be/9hhzCR0wDko?si=N8E1pmdVHUd3F7rw

**Comment by Alan5596** [comment] 2023-10-19 19:35
Thanks for the explanation and video which clearly has sorted the problem with the TCI and correct IF.

The problem I have is concerning SDC skimmer.   When it is running and you click on a CW trace thetis will change frequency but does not tune the radio to the frequency in the SDC waterfall.  For instance if I click on 28030 in the skimmer it will tune to around 1.2Khz higher and appears to vary by band.

I think this is the same problem referenced in Issue 62...

https://github.com/ramdor/Thetis/issues/62

I think if you contact Yuri the SDC author and explain that you are the Developer of Thetis he will most likely send you a key to let you install SDC with the TCI module enabled. That way you could replicate the issue maybe?

Thank you again for the excellent software and for your time in keeping it updated.

**Comment by ramdor** [comment] 2023-10-19 21:09
just tested here. All works ok.  https://youtu.be/MCCukj7irYI?si=gMFVQ9q5MTLopJ_j

Make sure you have IQ swap turned on in SDC

**Comment by Alan5596** [comment] 2023-10-20 13:43
That looks great and works perfectly.  Unfortunately there is no IQ swap button in any of the other OS versions, so it appears it is only present on the Linux version you have.  

I am happy to contact Yuri regarding this if you wish and see if he has any suggestions?

**Comment by ramdor** [comment] 2023-10-20 13:46
yes, it is the iq swap issue. Yuri very kindly just sent me a key for the new version and I have just emailed him ref the swap. If he doesn't want it in, then we will look at swapping in Thetis.

**Comment by Alan5596** [comment] 2023-10-20 13:48
Thank you, much appreciated.

**Comment by ramdor** [comment] 2023-10-20 14:34
Yuri has sent me a link to a new version where SwapIQ has returned. I think it will probably show up at some point in the future again. Perhaps drop him an email. Working very nicely here.

![image](https://github.com/ramdor/Thetis/assets/3124967/20245375-35f2-4372-9a71-8076e130807c)

**Comment by Alan5596** [comment] 2023-10-20 15:44
Looks great, look forward to getting the updated version.

**Comment by ramdor** [comment] 2023-10-21 07:48
closing as confirmed working, but sdc needs to use swapIQ

**Closed by ramdor** 2023-10-21 07:48 UTC
Labels: bug, enhancement

**Comment by ramdor** [comment] 2023-10-21 19:21
2.10.2.3 will have swapIQ option direct in Thetis for both vac1 and vac2

![image](https://github.com/ramdor/Thetis/assets/3124967/b56f15b6-0a25-43c7-a93b-6e85ae558d68)
