### ISSUE TITLE
[BUG] QPLT (Quick Split) does not engage MultiRX

### ISSUE THREAD

**Issue by rsaue** [ramdor/Thetis#186] opened 2023-10-06 18:16 UTC
Hi, 
I like the idea on the new Quick split feature. 

As I understand the tick options in setup->Options->Options 2, ticking the Enable MultiRX choice should also engage the MultiRX feature upon clicking on the QPLT button. 

Unfortunately, not at my site... 

![Thetis qsplit  and multirx](https://github.com/ramdor/Thetis/assets/22942440/8306ebb8-11b9-4f90-ba56-5a4ccc062be4)

73 de LB2EG Richard

**Comment by ramdor** [comment] 2023-10-06 19:59
it will only be applied when QPLT button is pressed/activated, not if already on and you add another qsplit option. Is this the issue?

**Comment by rsaue** [comment] 2023-10-06 20:37
Hi, 
the options was set before I engaged the QPLT button. It does make the split, move the TX to VFO B, and zoom in, but no MultiRX. To do MultiRX I have to manually klick on the MultiRX button. To be sure, I restarted Thetis, with no change in the described  Quick split behaviour. 

Richard

**Comment by ramdor** [comment] 2023-10-06 21:13
Hi Richard,

I have changed the order in which multiRX is applied. It would fail if vfoB freq was outside RX1 bandwidth. Now vfoB is moved, then multiRX applied.  I will push the changes later tonight if you want to recompile master branch and try it.

Cheers, R.

**Comment by rsaue** [comment] 2023-10-06 21:24
Hi, 
yes my VFO B was out of VFO A band. Readjusting the VFO B to VFO A band before engaging Quick split, makes MultiRX work "as advertised". I had no clue on that, thanks for fixing in later master update. 

As i said, I really like the Quick split feature. I have had this as a macro using DDUTIL since the Flexradio PowerSDR days, with one add on, that is putting VFO A sound on left ear and VFO B sound on right ear. A small feature request from me would be to make this an option in the Quick split menu. 

73 de LB2EG Richard

**Comment by ramdor** [comment] 2023-10-06 21:32
ah cood know that was the cause. I replicated the problem here, made the changes, and it works as expected. I will add options to set audio pan this evening.  Thanks for the tests and the reports. Cheers, Richie.

**Comment by ramdor** [comment] 2023-10-07 00:06
should be resolved in #188

**Closed by ramdor** 2023-10-07 00:06 UTC
Labels: bug
