### ISSUE TITLE
[BUG]  VAC list fails to fill

### ISSUE THREAD

**Issue by wa1oxt** [ramdor/Thetis#261] opened 2023-11-04 21:11 UTC
2.10.3.3 cannot select drivers Vac1. Last working update was 2.9.0.8
Win 11 Pro ,  i7 12gen Confirmed  by K2GX

![Screenshot 2023-11-04 162731](https://github.com/ramdor/Thetis/assets/26526956/c3a31049-7860-4d43-8ae5-da7bca4963a9)

**Comment by ramdor** [comment] 2023-11-04 21:32
What radio is being used?  It doesn't work on v.2.9.0.8 as tested below. I am not sure if there is meant to be some sort of sound driver installed to be able to use that, or if the radio has some sort of USB connection to the PC to be able to use it. The error from PortAudio is non 0, meaning there has been an error, even on v2.9.0.8.

![image](https://github.com/ramdor/Thetis/assets/3124967/9a312b41-4e50-45c4-9858-f7a3145ba28e)

**Comment by wa1oxt** [comment] 2023-11-04 23:19
My Radio is Anan 100d,K2GX  using 8000DLE
    On Saturday, November 4, 2023 at 05:32:35 PM EDT, Richie ***@***.***> wrote:  
 
 


What radio is being used? It doesn't work on v.2.9.0.8 as tested below. I am not sure if there is meant to be some sort of sound driver installed to be able to use that, or if the radio has some sort of USB connection to the PC to be able to use it. The error from PortAudio is non 0, meaning there has been an error, even on v2.9.0.8.

**Comment by ramdor** [comment] 2023-11-05 01:24
what does this vac device actually do?

**Comment by wa1oxt** [comment] 2023-11-05 02:17
I have no clue !.... Update 2.9.0.8 works fine. 2.10. x forward will not allow any other Driver options ie:ASIO / WDM / WDM.KS / MME / WASAPI .The darn thing is stuck on HPSDR (USB / UDP) option .
gary/oxt

    On Saturday, November 4, 2023 at 09:24:24 PM EDT, Richie ***@***.***> wrote:  
 
 


what does this vac device actually do?

**Comment by ramdor** [comment] 2023-11-05 02:31
oh so the problem is not that this wont do anything. The problem is that you dont get your vac devices listed?   Are you certain you are using 2.10.3.3  ?

**Comment by wa1oxt** [comment] 2023-11-05 02:41
Yes ,no devices listed ( only that HPSDR(USB/UDP). Yes running 2.10.3.3. Only way is to go back to 2.9.0.8 .Something must have changed the VAC-1/2 forward of 2.9.0.8.
gary
    On Saturday, November 4, 2023 at 10:31:37 PM EDT, Richie ***@***.***> wrote:  
 
 


oh so the problem is not that this wont do anything. The problem is that you dont get your vac devices listed? Are you certain you are using 2.10.3.3 ?

**Comment by wa1oxt** [comment] 2023-11-05 02:45
Richie , The Device window never opens, stuck on that HPSDR driver. 
    On Saturday, November 4, 2023 at 10:31:37 PM EDT, Richie ***@***.***> wrote:  
 
 


oh so the problem is not that this wont do anything. The problem is that you dont get your vac devices listed? Are you certain you are using 2.10.3.3 ?

**Comment by ramdor** [comment] 2023-11-05 02:51
do you see this message when you start thetis?

There was an issue initialising PortAudio

**Comment by wa1oxt** [comment] 2023-11-05 02:57
NO... No error. my first post is what is see. if I select "Driver" it does not change. Does not open .
gary
    On Saturday, November 4, 2023 at 10:51:20 PM EDT, Richie ***@***.***> wrote:  
 
 


do you see this message when you start thetis?

There was an issue initialising PortAudio

**Comment by ramdor** [comment] 2023-11-05 03:00
try disabling any sound devices not in use on your system. Port audio has been updated in 2.10.3 and it might be failing on some device that is not in use

**Comment by wa1oxt** [comment] 2023-11-05 03:12
No Joy.... Same Same. Was Port Audio updated b4 2.10.3 ?
    On Saturday, November 4, 2023 at 11:00:48 PM EDT, Richie ***@***.***> wrote:  
 
 


try disabling any sound devices not in use on your system. Port audio has been updated in 2.10.3 and it might be failing on some device that is not in use

**Comment by ramdor** [comment] 2023-11-05 03:12
yes port audio was updated in 2.10.3

**Comment by ramdor** [comment] 2023-11-05 03:15
some audio driver has to be causing this issue and the newer PA is failing on it. If you have disabled all audio devices not in use using device manager, then I would update the the drivers for devices that are in use.

**Comment by wa1oxt** [comment] 2023-11-05 03:16
Well maybe a bit was droped somewhere.
gary
    On Saturday, November 4, 2023 at 11:12:49 PM EDT, Richie ***@***.***> wrote:  
 
 


yes port audio was updated in 2.10.3

**Comment by ramdor** [comment] 2023-11-05 03:17
i use the old control panel even on Win11 to disable stuff. Not sure where the equivalent is in Windows11 sound gui. Right click on the device to disable.

![image](https://github.com/ramdor/Thetis/assets/3124967/cee51254-690a-4bcd-8abc-b26bef0f1f91)

**Comment by wa1oxt** [comment] 2023-11-05 03:19
Ok I will try that... up for a few hrs 2nite
tnxgary
    On Saturday, November 4, 2023 at 11:15:39 PM EDT, Richie ***@***.***> wrote:  
 
 


some audio driver has to be causing this issue and the newer PA is failing on it. If you have disabled all audio devices not in use using device manager, then I would update the the drivers for devices that are in use.

**Comment by wa1oxt** [comment] 2023-11-05 03:21
Same control panel..
give me a few mins to get bk to u
gary
    On Saturday, November 4, 2023 at 11:18:09 PM EDT, Richie ***@***.***> wrote:  
 
 


i use the old control panel even on Win11 to disable stuff. Not sure where the equivalent is in Windows11 sound gui. Right click on the device to disable.

**Comment by ramdor** [comment] 2023-11-05 03:21
disable everything other than your primary soundcard and vac cables.  Playback and Record tabs

**Comment by wa1oxt** [comment] 2023-11-05 03:33
1. Drivers update ok. 2. only UR22MKII now active in Sound Control Panel3. VAC now works .4.Can open VAC-1 and select Steinberg.
gary
    On Saturday, November 4, 2023 at 11:22:08 PM EDT, Richie ***@***.***> wrote:  
 
 


disable everything other than your primary soundcard and vac cables. Playback and Record tabs

**Comment by ramdor** [comment] 2023-11-05 03:36
ok, that is good news in a way. Now, if you want to experiment and narrow it down, you could enable each in turn, and try, until it fails. Do the Playback and Record for each device at the same time.  Entirely up to you.

**Comment by wa1oxt** [comment] 2023-11-05 03:39
OK...Keep u posted as I proceed
TnxGary
    On Saturday, November 4, 2023 at 11:36:22 PM EDT, Richie ***@***.***> wrote:  
 
 


ok, that is good news in a way. Now, if you want to experiment and narrow it down, you could enable each in turn, and try, until it fails. Do the Playback and Record for each device at the same time. Entirely up to you.

**Comment by wa1oxt** [comment] 2023-11-05 04:25
OK here's the scoop....For years I autostart a Virtual Mixer when Windows comes up. Use it for Youtube, Protools  etc.Always worked with PwrSdr/Thetis. Present issue started forward of 2.9.0.8, Going back to 2.9.0.8 all works well.Now Found that in order to run Thetis have to..
1.Restart Computer.2,Stop autostart of Virtual Mixer.3.Start Thetis.4,Start Virtual Mixer.5 Stop/Start VAC-1 6. Restart DAW.
Don't know the root cause of this problem,but do know that  reeling back the film to 2.9.0.8 solves it.
So, some joy in a way that you noticed a Port Audio Change in an Update.Not sure where to go from here.
up for a few hrs
gary

    On Saturday, November 4, 2023 at 11:36:22 PM EDT, Richie ***@***.***> wrote:  
 
 


ok, that is good news in a way. Now, if you want to experiment and narrow it down, you could enable each in turn, and try, until it fails. Do the Playback and Record for each device at the same time. Entirely up to you.

**Comment by ramdor** [comment] 2023-11-05 04:28
which virtual mixer are you using?  Yes I updated from the 2008 Port Audio, to the one released in 2021 for 2.10.3.

**Comment by wa1oxt** [comment] 2023-11-05 04:32
Oh good..still with me..Voicemeeter Potato.
    On Sunday, November 5, 2023 at 12:28:54 AM EDT, Richie ***@***.***> wrote:  
 
 


which virtual mixer are you using? Yes I updated from the 2008 Port Audio, to the one released in 2021 for 2.10.3.

**Comment by ramdor** [comment] 2023-11-05 04:37
well there are 2 options

1) stay with 2.9.0.8
2) perform the jiggle to get it working with the newer portaudio and 2.10.3.3

I have no real idea why the get devices would return 0 other than a bad driver that the newer portaudio has issues with. I also run Potato here, but I dont auto start it at windows start. I will try that shortly.

**Comment by ramdor** [comment] 2023-11-05 04:44
with VM Potato x64 configured to run at start up I have no issues

![image](https://github.com/ramdor/Thetis/assets/3124967/a33cae41-f6a9-46a3-a069-3d59dfac4377)

**Comment by wa1oxt** [comment] 2023-11-05 04:53
Yes 2.9.0.8 is an option. Love 2.10.3.3 !Ya , know the dance (jiggle) . What's interesting is my other 100d on a win10 machine (12yr old) works fine with 2.10.3.3 and autostart of VMP etc.
gary


    On Sunday, November 5, 2023 at 12:37:32 AM EDT, Richie ***@***.***> wrote:  
 
 


well there are 2 options
   
   - stay with 2.9.0.8
   - perform the jiggle to get it working with the newer portaudio and 2.10.3.3

I have no real idea why the get devices would return 0 other than a bad driver that the newer portaudio has issues with. I also run Potato here, but I dont auto start it at windows start. I will try that shortly.

**Comment by ramdor** [comment] 2023-11-05 04:56
yes you probably have some old driver hiding away there. If you can, remove all sound devices from device manager, then reboot, let it find them all again, and update drivers if necessary?

![image](https://github.com/ramdor/Thetis/assets/3124967/4788832e-9920-4fc0-9159-f7634e6628e3)

**Comment by wa1oxt** [comment] 2023-11-05 05:02
r u running win11 23H2, same VMP here 3.0.2.8 (64 bit) ?Not to bend it a bit BUT Joe ,K2GX is having the same problem.Was Port Audio changed from 2.9.0.8 to 2.10,x ?

    On Sunday, November 5, 2023 at 12:44:24 AM EDT, Richie ***@***.***> wrote:  
 
 


with VM Potato x64 configured to run at start up I have no issues

**Comment by ramdor** [comment] 2023-11-05 05:05
yes 2.10.3 had new portaudio version. It is in the release notes.  22H2 here, Windows 11 Pro

**Comment by wa1oxt** [comment] 2023-11-05 05:06
OK, will give it a go and return in the morning.Thank you for the help...been interesting
Follow up later today73gary
    On Sunday, November 5, 2023 at 12:56:42 AM EDT, Richie ***@***.***> wrote:  
 
 


yes you probably have some old driver hiding away there. If you can, remove all sound devices from device manager, then reboot, let it find them all again, and update drivers if necessary?

**Comment by wa1oxt** [comment] 2023-11-05 05:27
Ok tnx Richie
gary
    On Sunday, November 5, 2023 at 01:05:27 AM EDT, Richie ***@***.***> wrote:  
 
 


yes 2.10.3 had new portaudio version. It is in the release notes. 22H2 here, Windows 11 Pro

**Comment by ramdor** [comment] 2023-11-05 23:53
nothing I can do about this right now, we might have to wait for a new port audio release. I would uninstall everything audio related, drivers and all, and rebuild that part of your pc. Closing for now as nothing more I can advise on or do.

**Closed by ramdor** 2023-11-05 23:53 UTC
Labels: bug

**Comment by wa1oxt** [comment] 2023-11-06 00:02
oktnx richie
    On Sunday, November 5, 2023 at 06:54:05 PM EST, Richie ***@***.***> wrote:  
 
 


Closed #261 as completed.

**Comment by wa1oxt** [comment] 2023-11-06 00:03
OKtnx Richie
    On Sunday, November 5, 2023 at 06:54:06 PM EST, Richie ***@***.***> wrote:  
 
 


nothing I can do about this right now, we might have to wait for a new port audio release. I would uninstall everything audio related, drivers and all, and rebuild that part of your pc. Closing for now as nothing more I can advise on or do.
