### ISSUE TITLE
[BUG] No audio out speaker or headphone jacks 

### ISSUE THREAD

**Issue by n9bc** [ramdor/Thetis#492] opened 2024-08-16 14:08 UTC
**Describe the bug**
No audio output from the speaker or headphone jacks on G2 no display.

Versions affected that I have tested
2.10.3.6 dev_8b
2.10.3.5 

Working version
2.10.3.4

**Comment by ramdor** [comment] 2024-08-16 14:16
have you tried checking/unchecking this, in setup/audio/options

![image](https://github.com/user-attachments/assets/77f95f23-49f4-482a-b1fa-99ca68744375)

**Comment by n9bc** [comment] 2024-08-16 14:21
I did check that as well.

**Comment by laurencebarker** [comment] 2024-08-16 14:38
Sorry but I can't reproduce this here. What firmware and p2app version do you have?  Mine is firmware version 17, p2app version 27 and speaker audio is fine.

If this persists, can you plug in a keyboard, mouse and monitor and run the audiotest app? That will tell whether the hardware on the board is working.

**Comment by ramdor** [comment] 2024-08-16 14:39
@n9bc just a quickie, are you using CMASIO as that was introduced in 2.10.3.5?

**Comment by n9bc** [comment] 2024-08-16 15:07
That was the issue CMASIO was still configured in the registry. I removed it and the issue went away.

**Comment by ramdor** [comment] 2024-08-16 15:34
glad it is resolved @n9bc . Closing.

**Closed by ramdor** 2024-08-16 15:34 UTC
Labels: bug
