### ISSUE TITLE
FM tx/rx AF filters in DSP FM tab [BUG]

### ISSUE THREAD

**Issue by Roturbo** [ramdor/Thetis#262] opened 2023-11-05 03:43 UTC
Thetis V2.10.3

**Describe the bug**
There is a noticeable change in sound if we change the filter from 300 to 10Hz, 
but on transmit it looks that audio don´t go below 200Hz .

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'DSP'
2. Click on 'FM'
3. Chose "Remove CTCSS Tone" set TX and RX to 10hz Low to 3000 High, also adjusted EQ and TX profile to match filter.
4. Pre-emphasize before limiting activated
5. Like in picture, on SSB the voice is very close to center of filter, on FM there is always a gap like an attenuation to 200Hz

**Expected behaviour**
Checked with other analog radios and they deliver audio to the center of filter, 
using Thetis the lack of low frequencies is as clear on sound as in picture.

**Screenshots**
![settings](https://github.com/ramdor/Thetis/assets/91867260/929c62b0-20b7-4e5f-8515-6eb2f123bd5e)

![compare](https://github.com/ramdor/Thetis/assets/91867260/e5df6321-6280-49ff-85dd-6e926c50cd7e)

**Desktop (please complete the following information):**
 - OS: [ Windows10]

**Additional context**
Is there any way the audio must be treated different from SSB to FM ?

Regards

**Comment by RdWing** [comment] 2023-11-05 19:30
Remove CTCSS tone is by option going to remove some of the low audio, just  because that's where the CTCSS tones live.

**Comment by Roturbo** [comment] 2023-11-05 22:47
Hello, i did try with and without it, is the same,, the cut goes very close to 250hz, the faded vertical
lines on Spectrum are 500hz each and it is almost at center.

I´m using a 100D, do you have the same image with your radio ?

**Comment by ramdor** [comment] 2023-11-05 23:49
@Roturbo the notch for CTCSS frequency is just that, a very narrow notch at that.

The cause of this issue is that TX was not fully tested before it was released. WDSP needed some fixes, as did Thetis console. After the fixes, this is the result, and will be in 2.10.3.4 at some point in next couple of weeks.

https://youtu.be/vn2rW_g_RVQ?si=YIBC2JJ3Xy2E0L6u

Richie.

**Comment by Roturbo** [comment] 2023-11-06 02:46
Hello Richei, 

tanks for your replay, that´s it, we just need to have patience and wait for next release,
that for sure will bring many other bugs fixed and new improvements. 

Regards.

**Comment by ramdor** [comment] 2023-11-08 07:26
closed, will be available/fixed for 2.10.3.4

**Closed by ramdor** 2023-11-08 07:26 UTC
Labels: bug

**Comment by Roturbo** [comment] 2023-11-11 03:34
Hello to all,

yes, 2.10.3.4 now it is working, no more low cut, maybe is only missing audio Monitor in FM.

![1](https://github.com/ramdor/Thetis/assets/91867260/468a3f32-ee75-471d-964d-3a5674b4c28b)



Regards, and again tanks to all involved.
