### ISSUE TITLE
Thetis Support for Elad TM-2 USB controller

### ISSUE THREAD

**Issue by Goldfish246** [ramdor/Thetis#532] opened 2024-11-21 20:00 UTC
I love my Hermes Lite 2 Plus transceiver

But I love a big VFO knob instead of a mouse.

I've used other options but I want to use my Elad TM-2 USB controller.

Please let me know if any support is being done to use Elad with Thetis.

Any kind of patch or software development in the works for this? Elad works with other sdr programs but Thetis is the best.

73, Steve KQ6ZJ

**Comment by DH1KLM** [comment] 2024-11-24 10:45
As long as you use Tmate2CatConsole.exe, there should be no problem with Thetis. In Tmate2CatConsole, simply select PowerSDR.

![image](https://github.com/user-attachments/assets/65dbd072-5500-4a99-8727-ea59220da617)

**Comment by Goldfish246** [comment] 2024-11-24 14:08
Thank you for your help. So I used the ELAD in SDR Console 3 just by plugging it in and going to controllers in the Console menu. 

I'm having a hard time here. Downloaded the ELAD Tmate controller software from ELAD but when I try to run it its saying I'm missing a msvcr100.dll driver.

I'll need some help with the virtual com port driver too if you can.

Your help is most appreciated.

73,

Steve
KQ6ZJ

**Comment by DH1KLM** [comment] 2024-11-24 16:03
For missing msvcr100.dll you need VC_Redist runtime packages for Visual C++ installed.
https://aka.ms/vs/17/release/vc_redist.x64.exe

I am using VSPE from K5FR. Ham Radio operators get it free for personal use.
https://k5fr.com/DDUtilV3wiki/index.php?title=VSP_Manager

If you have any further questions, use my email address on qrz.com.

**Comment by ramdor** [comment] 2024-11-24 16:31
closing this, as duplicate of this https://github.com/ramdor/Thetis/issues/276 . Github is not tech support, it is a place to report issues/bugs/new features, AFTER the existing ones have been searched.

**Closed by ramdor** 2024-11-24 16:31 UTC
Labels: enhancement
